# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MotivityV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MotivityV2

	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'

  target 'MotivityV2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MotivityV2UITests' do
    # Pods for testing
  end

end
